name: 3dunet-centroid
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cloudpickle=1.5.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.24.0
  - decorator=4.4.2
  - expat=2.2.9
  - freetype=2.10.2
  - icu=58.2
  - intel-openmp=2020.2
  - jpeg
  - kiwisolver=1.2.0
  - lcms2=2.11
  - libffi=3
  - libpng=1.6.37
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - networkx=2.5
  - olefile=0.46
  - openssl=1.1.1g
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.10
  - python-dateutil
  - pyyaml=5.3.1
  - qt=5.9.7
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.10.0
    - astor==0.8.1
    - connected-components-3d==1.8.0
    - gast==0.4.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - imageio==2.9.0
    - importlib-metadata==1.7.0
    - joblib==0.16.0
    - keras==2.1.6
    - keras-applications==1.0.8
    - git+https://www.github.com/keras-team/keras-contrib.git
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - mat73==0.46
    - matplotlib==3.3.1
    - nibabel==2.4.0
    - nilearn==0.6.2
    - numexpr==2.7.1
    - numpy==1.16.0
    - opencv-python==4.2.0.32
    - pydot==1.4
    - protobuf==3.13.0
    - pywavelets==1.1.1
    - scikit-image==0.16.2
    - scikit-learn==0.23.2
    - scipy==1.2.1
    - simpleitk==1.2.0
    - sklearn==0.0
    - tables==3.6.1
    - tensorboard==1.12.2
    - tensorflow-gpu==1.12.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - werkzeug==1.0.1
    - zipp==3.1.0
prefix: /home/ok37/miniconda3/envs/3dunet-centroid
